Linters-Config
davmba/HELLO--Microverse pull request #1
Opened 2022-09-21 14:25 UTC by davmba

### My first Microverse project.
**In this project:**

- A repo was created
- A branch was created from the main
- linters files were added to the branch and 
- A pull request was created

2022-09-21 14:44 UTC, Abenezer-Tilahun requested changes
Hi @davmba   , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Github Flow.
✔️ Good commit messages


## Required Changes ♻️

- [ ] Please try to Add descriptive  README file to your project. Kindly add your GitHub and LinkedIn username at the author section and fix the MIT License link in your readme file, the Link is broken if you don't have License you can remove it.

- [ ]  Kindly make sure your PR has a descriptive summary (details) describing introduced changes in more detail. To do that you can click on the three dots of the description box. see the screen shoot of the box on the screenshot below ⬇️ and click edit and you will be able to write.

![Capture](https://user-images.githubusercontent.com/93598189/191534702-dcfb4609-0947-43b2-b575-90bfa9935e68.PNG)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 15:42 UTC, HAMMAS-SALEEM requested changes
# Welcome to Microverse :tada: :tada: :bouquet: :bouquet:
# Required Changes :recycle:

![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @davmba :wave:

## Highlights :1st_place_medal:

:heavy_check_mark: Following GitHub Flow
:heavy_check_mark: Following Linters
:heavy_check_mark: Following Some Requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 15:42 UTC, HAMMAS-SALEEM commented on .github/workflows/linters.yml
> +
### Descriptive Summary Example :heavy_check_mark:
![hammas-summary](https://user-images.githubusercontent.com/93039359/176921727-17499afe-c29c-47f8-823e-a3cfc70feae1.png)

- [ ] You don't have a summary for your project. You can see the image above to get an idea of what a descriptive summary looks like. The summary tells in detail what are you doing in this pull request and why. :thinking:

2022-09-22 00:26 UTC, Reem-lab approved these changes
# Hi @davmba,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯
<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>


## Highlights ✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the functionality✅
📌 Good commit messages ✅
📌Professional README ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 01:00 UTC, merged